export const projectsList = [
  {
    id: 1,
    name: "Metricks",
    description:
      "Metricks is an affiliate tracking software developed to provide small and medium scale enterprises with the solution they need to grow and scale their affiliate marketing.",
    image: "/images/metricks.png",
    mobileImage: "/images/metricks.png",
    link: "https://www.metricks.io/",
    GitHub: "",
    project: "Metricks",
    tools: ["Node.js", "Express.js", "PostgreSQL", "TypeScript", "Mocha", "Chai", "AWS"],
  },
  {
    id: 9,
    name: "mDoc LMS",
    description: "mDoc LMS is a mobile app for health professionals, offering personalized learning paths and access to the latest medical research. Users can track their progress, earn certifications, and meet professional standards. The platform fosters a global community dedicated to advancing health education.",
    image: "/images/lms.jpeg",
    mobileImage: "/images/lms.jpeg",
    link: "https://play.google.com/store/apps/details?id=com.mDoc.lms&hl=en",
    GitHub: "",
    project: "mDoc LMS",
    tools: ["NestJs", "AWS", "NodeJs", "MongoDb", "React Native"],
  },
  {
    id: 10,
    name: "Navihealth AI",
    description: "NaviHealth™ is an online directory of health services, facilities and providers powered by mDoc. mDoc is a digital health company focused on sub-Saharan Africa which provides people living with chronic health needs with 24/7 access to integrated care support through a network of providers via mobile and web platforms. ",
    image: "/images/navihealth.png",
    mobileImage: "/images/navihealth.png",
    link: "https://navihealth.ai/",
    GitHub: "",
    project: "Navihealth AI",
    tools: ["NestJs", "AWS", "NodeJs", "MongoDb", "ReactJs"],
  },
  {
    id: 2,
    name: "Covid-19 Tracker",
    description:
      "Covid-19 Tracker is a web application that allows users to track the latest updates on the COVID-19 pandemic. Its main purpose is to provide a platform for users to stay informed about the latest updates on the virus. Its features a light and dark mode, a search bar, and a filter bar.",
    image: "/images/covid-19.png",
    mobileImage: "/images/covid-19.png",
    link: "https://covid-19-tracker-3317f.web.app/",
    GitHub: "https://github.com/Youngprinnce/covid-19-tracker",
    project: "Covid-19 Tracker",
    tools: ["React.js", "Material-Ui", "Chart.js", "Firebase"],
  },
  {
    id: 6,
    name: "Nosh",
    description:"Nosh is a FinTech product that offers easy and quick transactions for anyone. Equipped with modern and seamless means of payment, Nosh offers the easiest and most convenient way for you to buy gift card and sell gift card in Nigeria, buy airtime and data, virtual cards, and loads of other products, whatever they may be.",
    image: "/images/nosh.png",
    mobileImage: "/images/nosh.png",
    link: "https://nosh.ng/",
    project: "Nosh",
    tools: ["NodeJs", "MongoDB", "Redis", "AWS", "ExpressJS"],
  },
  {
    id: 7,
    name: "File-Share",
    description:
      "File-Share is a web application that allows users to share files with other users. This is a mini app that allows you share files of up to100mb between your family and friends. All you do is upload the file and you get the link to the uploaded file, you can also send an the file as an email to anyone you like.",
    image: "/images/file-share.png",
    mobileImage: "/images/file-share.png",
    link: "https://youngprinnce.github.io/file-share-frontend/",
    GitHub: "https://github.com/Youngprinnce/file-share",
    project: "FIle-Share",
    tools: ["Node.js", "HTML", "CSS", "JavaScript"],
  },
  {
    id: 8,
    name: "Simple Bank",
    description:
      "Simple Bank is a Backend Application that allows users to manage their bank accounts. This is a mini app that allows you to manage your bank accounts and transactions. You can create an account, deposit, withdraw, transfer money, and record acounts entries.",
    image: "/images/bank.jpg",
    mobileImage: "/images/bank.jpg",
    link: "",
    GitHub: "https://github.com/Youngprinnce/simple-bank",
    project: "Simple Bank",
    tools: ["Golang", "Sqlc", "MakeFile", "Postman"],
  },
];
